### ISSUE TITLE
panic: unexpected token BlockEnd (}) 

### ISSUE THREAD

**Issue by p1v07** [tufanbarisyildirim/gonginx#16]
Part of my nginx conf:

```
 64     init_by_lua_block {
 65         local xxx= require 'xxx'
 66
 67         local config_file = "./conf/xxx.conf"
 68         local env_path = "/x/env.properties"
 69         local config = xxx.init({
 70             config = config_file,
 71             env = env_path
 72         })
 73
 74         context = {
 75             xxx= xxx,
 76             config = config
 77         }
 78     }
```

I already used the latest version:

```
require (
	github.com/tufanbarisyildirim/gonginx v0.0.0-20230325082000-26dcb15a9df4
)
```

the error:

```
panic: unexpected token BlockEnd (}) on line 72, column 9

goroutine 1 [running]:
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseStatement(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:212 +0x93b
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseBlock(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:164 +0xbc
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseStatement(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:205 +0x7a5
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseBlock(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:164 +0xbc
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseStatement(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:205 +0x7a5
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseBlock(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:164 +0xbc
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseStatement(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:205 +0x7a5
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).parseBlock(0xc000194000)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:164 +0xbc
github.com/tufanbarisyildirim/gonginx/parser.(*Parser).Parse(...)
        github.com/tufanbarisyildirim/gonginx/parser/parser.go:147

```

**Comment by ermazi** [comment]
solved?

**Comment by tufanbarisyildirim** [comment]
> solved?

I think @p1v07 closed cuz either it was by a mistake or solved by any other PR. Feel free to open a new one if you encounter the same issue
